default:
  golem_name: peskas.timor.portal
  golem_version: 0.0.0.9000
  app_prod: no
  mapbox_token: !expr readLines("auth/mapbox-token")
  storage:
    google:
      key: gcs
      options:
        project: peskas
        bucket: public-timor
        service_account_key: !expr readLines("auth/gcp-sa-peskas_ingestion-key.json")
production:
  app_prod: yes
  mapbox_token: !expr readLines("mapbox_token")
  storage:
    google:
      options:
        service_account_key: !expr Sys.getenv('GCP_SA_KEY')
dev:
  golem_wd: !expr here::here()
  storage:
    google:
      options:
        bucket: public-timor-dev
