on:
  push:
    branches:
      - main
      - master

env:
  RENV_PATHS_ROOT: ~/.local/share/renv
  R_CONFIG_ACTIVE: production
  GCP_SA_KEY: ${{ secrets.PESKAS_DATAINGESTION_GCS_KEY }}

jobs:
  deploy-shinyapps-io:
    name: Deploy on shinyapps.io
    runs-on: ubuntu-latest
    container: rocker/verse:4.1.0
    env:
      SHINYAPPS_TOKEN: ${{secrets.SHINYAPPS_TOKEN}}
      SHINYAPPS_SECRET: ${{secrets.SHINYAPPS_SECRET}}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("devtools"))'
          Rscript -e 'devtools::install_deps(dependencies = TRUE, update = "never")'

      - name: Update data
        run: |
          Rscript -e 'source("data-raw/aggregated.R")'
          Rscript -e 'source("data-raw/var_dictionary.R")'

      - name: Set shinyapps.io account info
        run: Rscript -e "rsconnect::setAccountInfo(name='worldfish', token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"

      - name: Push to shinyapps.io
        run: Rscript -e "rsconnect::deployApp(appName = 'peskas', appTitle = 'peskas', appFileManifest = 'appFileManifest')"
