on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '0 1 * * *'

name: Deploy Google Cloud Run

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: peskas-timor-shiny
  REGION: asia-east1
  CONTAINER_REGISTRY: asia.gcr.io

jobs:
  deploy:
    name: Deploy shiny app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true  # Set to true to authenticate the Cloud Run action

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and push API container
      run: |-
        docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} -f prod.Dockerfile .
        docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0.6.0
      with:
        service: ${{ env.SERVICE }}
        image: ${{ env.CONTAINER_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
        region: ${{ env.REGION }}
        flags: "--cpu=1 --memory=1Gi --concurrency=80 --max-instances=1"

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
